### ISSUE TITLE
Server rendering in dev

### ISSUE THREAD

**Issue by ghost** [ayoubdev/reactjs-starterkit#1]
Hi @ayoubdev 
Beau boulot :+1: 
How would you run isomorphic in dev mode ?

**Comment by adbayb** [comment]
Hello @naptiv , 
It has not been yet implemented since React Hot Loader only renders client side one.
Typically, dev mode is usefull if you want to have live reload on your webpage while coding. 
But there is no problem to use prod commands to bundle and test your isomorphic app before real prod deployment :)

**Comment by ghost** [comment]
Yep I figured out
